# Setup dependabot

version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directories:
      - "*"
      - "**"
    schedule:
      interval: "daily"
      day: "friday"
      time: "10:00"
      timezone: "Europe/Paris"
    allow:
      - dependency-name: "*"
        dependency-type: "all"
    rebase-strategy: "disabled"
  - package-ecosystem: "github-actions"
    directories:
      - "*"
      - "**"
    schedule:
      interval: "daily"
      day: "friday"
      time: "10:00"
      timezone: "Europe/Paris"
    allow:
      - dependency-name: "*"
        dependency-type: "all"
    rebase-strategy: "disabled"