[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
#build-std-features = ["compiler-builtins-mem", "compiler-builtins-c"]
build-std-features = ["compiler-builtins-mem"]

[alias]
bamd64 = [ "build", "--target=./llvm-targets/x86_64-unknown-kernel.json" ]

[build]
rustflags = ['--cfg', 'getrandom_backend="rdrand"' ]