cargo-features = ["profile-rustflags"]

[package]
name = "xtask"
edition = "2024"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
rustflags = ["-C", "target-cpu=native", "-Z", "macro-backtrace"]

[dependencies]
anyhow = { version = "1.0.98", features = ["backtrace"] }
camino = { version = "1.1.10", features = ["serde", "serde1"] }
clap = { version = "4.5.40", features = [
    "default",
    "derive",
    "env",
    "string",
    "unicode",
    "wrap_help",
] }
dirs = "6.0.0"
fs4 = { version = "0.13.1", features = ["smol"] }
phf = { version = "0.12.1", features = ["std", "macros"] }
regex = { version = "1.11.1", features = ["unstable", "perf-dfa-full"] }
rmp = "0.8.14"
rmp-serde = "1.3.0"
serde = { version = "1.0.219", features = ["default", "alloc", "derive", "rc", "unstable"] }
serde_with = "3.13.0"
tempfile = { version = "3.20.0", features = ["nightly"] }
which = { version = "8.0.0", features = ["regex"] }
