cargo-features = ["profile-rustflags"]

[package]
name = "xtask"
edition = "2024"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
rustflags = ["-C", "target-cpu=native"]

[dependencies]
clap = { version = "4.5.40", features = [
    "default",
    "derive",
    "env",
    "string",
    "unicode",
    "wrap_help",
] }
