#ifndef zerOS_KLIBC_DETAIL_OVERLOAD_H_INCLUDED
#define zerOS_KLIBC_DETAIL_OVERLOAD_H_INCLUDED

#undef  __KLIBC_OVERLOAD_FN_FILTER_BY_PROVIDED_ARGCOUNT
#define __KLIBC_OVERLOAD_FN_FILTER_BY_PROVIDED_ARGCOUNT(count, ...) \
    

#endif
