## Timeout in seconds that Limine will use before automatically booting.
#TIMEOUT=10
#
## The entry name that will be displayed in the boot menu.
#:zerOS
#    # We use the Limine boot protocol.
#    PROTOCOL=limine
#
#    # Disable KASLR (it is enabled by default for relocatable kernels)
#    KASLR=no
#
#    # Path to the kernel to boot. boot:/// represents the partition on which limine.cfg is located.
#    KERNEL_PATH=boot:///boot/zerOS
#
# Same thing, but with KASLR.
#:zerOS (with KASLR)
#    PROTOCOL=limine
#
#    KASLR=yes
#
#    KERNEL_PATH=boot:///boot/zerOS

# Timeout in seconds that Limine will use before automatically booting.
timeout: 10

# The entry name that will be displayed in the boot menu.
/zerOS
    # We use the Limine boot protocol.
    protocol: limine

    #randomise_hhdm_base: yes
    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    kernel_path: boot():/boot/zerOS.stripped
