cargo-features = ["different-binary-name"]

[package]
name = "zerOS-kernel"
description = "The zerOS kernel"
version = "0.1.0"
authors = ["Axel PASCON <axelpascon@nullware.dev>"]
edition = "2024"
homepage = "https://github.com/brvtalcake/zerOS"
repository = "https://github.com/brvtalcake/zerOS"
license-file = "../LICENSE"
readme = "../README.md"

autobins = false
autoexamples = false
autotests = false
autobenches = false

#[lib]
#name = "zerOS"
#crate-type = [ "rlib", "staticlib" ]
#doc = true

[[bin]]
name = "zerOS"
filename = "zerOS"
path = "./src/main.rs"
doc = true

#[features]
#default = ["limine-bootloader"]
#limine-bootloader = []
#grub2-bootloader = []
#uefi-bootloader = []

[dependencies]
overloadable = "0.4"
cfg-if = "1"
fastdivide = "0.4.2"
bitflags = "2.9"
itertools = { version = "0.14", default-features = false }
hashbrown = "0.15"
itoa = "1.0"
ryu = "1.0"
scopeguard = { version = "1.2", default-features = false }
cpufeatures = "0.2"
memoffset = "0.9"
getrandom = "0.3"
time = { version = "0.3", default-features = false }
zerocopy = { version = "0.8", default-features = false, features = ["derive"] }
limine = "0.4"
x86 = "0.52.0"
compiler_builtins = "*"
paste = "1.0.15"
#static_assertions = "1.1.0"
bytemuck = "1.22.0"
bitfrob = "1.3.2"
lru = "0.14.0"
raw-cpuid = "11.5.0"
#ctor_bare = "0.2.1"
goblin = { version = "0.9", default-features = false }
gimli = { version = "0.31", default-features = false }
either = { version = "1.15.0", default-features = false }
lazy_static = { version = "1.5", features = ["spin_no_std"] }
multiboot2 = "0.23"
phf = { version = "0.11", default-features = false, features = [
    "macros",
    #"serde",
    "uncased",
    "unicase",
] }
strum = { version = "0.27", default-features = false, features = [
    "derive",
    #"phf",
] }
bincode = { version = "2.0.1", default-features = false }
intrusive-collections = { version = "0.9", features = ["alloc", "nightly"] }
strength_reduce = "0.2.4"
#bitfield = "0.19"
x86_64 = "0.15"
zerOS-proc-macro-utils = { path = "../proc-macro-utils" }
zerOS-macro-utils = { path = "../macro-utils" }
#overloadf = "0.1.8"
overloadf = { git = "https://github.com/brvtalcake/overloadf.git", branch = "public-overloads" }
critical-section = { version = "1.2", default-features = false }
#backtrace = { version = "0.3", default-features = false }
anyhow = { version = "1.0", default-features = false }
#bitfield-struct = "0.10.1"
anstyle = { version = "1.0.10", default-features = false }
downcast-rs = { version = "2.0.1", default-features = false }
psm = "0.1"
logos = { version = "0.15.0", default-features = false, features = [
    "export_derive",
] }

[dependencies.log]
version = "0.4.27"
features = ["kv"]

[dependencies.uuid]
version = "1.16"
default-features = false
features = ["rng-getrandom", "v1", "v3", "v4", "v5", "v6", "v7", "v8"]

[dependencies.rustc-demangle]
version = "0.1.16"
default-features = false

[dependencies.libm]
version = "0.2"
default-features = false
features = ["force-soft-floats", "unstable"]

[dependencies.num-traits]
version = "0.2"
default-features = false
features = ["libm", "i128"]

[dependencies.serde]
version = "1.0"
default-features = false
features = ["derive", "unstable"]

[dependencies.byteorder]
version = "*"
default-features = false
features = ["i128"]

[dependencies.rmp]
version = "0.8"
default-features = false

#[dependencies.defmt]
#version = "1.0"
#default-features = false

[dependencies.postcard]
version = "1.1"
default-features = false
#features = ["use-crc", "use-defmt", "experimental-derive", "heapless"]
features = ["use-crc", "experimental-derive", "heapless"]

[dependencies.heapless]
version = "0.8"
default-features = false
features = ["portable-atomic-critical-section"]

[dependencies.portable-atomic]
version = "1.11"
features = ["critical-section"]

[dependencies.unwinding]
version = "0"
default-features = false
features = [
    "unwinder",
    "fde-static",
    "personality",
    "panic",
    "dwarf-expr",
    "hide-trace",
]

[dev-dependencies]

#[target]

[build-dependencies]
cc = "1.2.18"
toml = "*"
strum = { version = "0.27", default-features = true, features = ["derive"] }
serde = { version = "*", default-features = true, features = ["derive"] }
autocfg = "1.4.0"
#bindgen = "0.71.1"
#jobserver = "0.1.33"
#cpp = "0.5.10"
#cpp_build = "0.5.10"
cfg_aliases = "0"

zerOS-proc-macro-utils = { path = "../proc-macro-utils" }
zerOS-macro-utils = { path = "../macro-utils" }

[profile.dev]
opt-level = 0
debug = "full"
split-debuginfo = "off"
strip = "none"
debug-assertions = true
overflow-checks = true
lto = "off"
panic = "abort"
incremental = true
#codegen-units = 256
rpath = false

[profile.release]
opt-level = 3
debug = false
split-debuginfo = "packed"
strip = "none"
debug-assertions = false
overflow-checks = false
lto = false
panic = "abort"
incremental = false
#codegen-units = 16
rpath = false

[profile.release-lto]
inherits = "release"
lto = true

[profile.dev-lto]
inherits = "dev"
lto = true
incremental = false
